cf integration git auth
codefresh-io/cli-v2 pull request #316
Opened 2022-03-17 20:30 UTC by andrii-codefresh

2022-03-21 15:36 UTC, pasha-codefresh requested changes

2022-03-21 15:36 UTC, pasha-codefresh commented on cmd/commands/integrations.go
> +	user, err1 := cfConfig.GetCurrentContext().GetUser(ctx)
rename from err1

2022-03-21 15:36 UTC, pasha-codefresh commented on cmd/commands/integrations.go
> +	userId := user.ID
dont think that you need this variable

2022-03-21 15:36 UTC, pasha-codefresh commented on cmd/commands/integrations.go
> +	for i := range user.Accounts {
move it to account util, or another util

2022-03-21 15:36 UTC, pasha-codefresh commented on cmd/commands/integrations.go
> +	runtime, err2 := cfConfig.NewClient().V2().Runtime().Get(ctx, runtimeName)
err2 -> err

2022-03-21 15:36 UTC, pasha-codefresh commented on cmd/commands/integrations.go
> +	if !strings.HasPrefix(*runtime.IngressHost, "http") {
move it to util, like OPenBrowser function

2022-03-21 15:36 UTC, pasha-codefresh commented on cmd/commands/integrations.go
> +	err3 := browser.OpenURL(url)
err3 -> err

2022-03-21 19:49 UTC, pasha-codefresh approved these changes

2022-03-21 19:49 UTC, pasha-codefresh commented on cmd/commands/integrations.go
> +	"os"
this will cause linter issues

2022-03-23 10:36 UTC, andrii-codefresh commented
/e2e

2022-03-23 10:43 UTC, roi-codefresh commented on pkg/util/util.go
> +	b.WriteString("/app-proxy/api/git-auth/github?userId=" + user + "&accountId=" + account)
You should use `https://pkg.go.dev/net/url`

2022-03-23 11:50 UTC, roi-codefresh approved these changes

2022-03-23 14:16 UTC, merged